version: '3'
services:
  db:
    image: 'postgres:13-alpine'
    env_file: .env.development
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -b 0.0.0.0 -p 80
    env_file: .env.development
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
volumes:
  postgres: