default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST') {'localhost'} %>
  username: <%= ENV.fetch('POSTGRES_USERNAME') {'postgres'} %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') {'93pbf34K8p7A'} %>

development:
  <<: *default
  database: parking_system_development

test:
  <<: *default
  database: parking_system_test

production:
  <<: *default
  database: parking_system_production
  username: parking_system
  password: <%= ENV["PARKING_SYSTEM_DATABASE_PASSWORD"] %>
